# ROBO-MARC Project web page style (Jekylll slate)
# https://github.com/pages-themes/slate 
#
theme: jekyll-theme-cayman
title: [NEDO ROBO-MARC]
description: [NEDO ROBO-MARC (Robot Platformization) Project Web page]
